# Generated by Django 3.2.5 on 2021-10-11 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(default='user-slug-field', editable=False)),
                ('profile_picture', models.ImageField(default='users_profile_picture/default_user_image.png', upload_to='users_profile_picture')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('social_twitter', models.URLField(blank=True, null=True)),
                ('social_facebook', models.URLField(blank=True, null=True)),
                ('social_linkedin', models.URLField(blank=True, null=True)),
                ('social_github', models.URLField(blank=True, null=True)),
                ('social_instagram', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
