# Generated by Django 3.2.5 on 2021-10-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211013_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_github',
            new_name='social_youtube',
        ),
    ]
