# Generated by Django 3.2.5 on 2021-10-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_social_github_profile_social_youtube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='social_whatsapp',
        ),
    ]
