# Generated by Django 3.2.5 on 2021-10-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_website_profile_social_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
