# Generated by Django 3.2.6 on 2021-10-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users_profile_picture/default_user_image.png', null=True, upload_to='users_profile_picture'),
        ),
    ]
