# Generated by Django 3.2.5 on 2021-10-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_post_image.jpg', null=True, upload_to='posts'),
        ),
    ]
