# Generated by Django 3.2.5 on 2021-10-29 13:08

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
